# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "s3-wrapper-upgrade" ]

jobs:
  build:

    runs-on: windows-latest

    env:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test
    - name: Copy coverage report
      run: |
          mkdir -p coverage
          cp my-app/AWS.S3.Wrapper.Tests/TestResults/*/coverage.cobertura.xml coverage/coverage.cobertura.xml

    - name: Install cURL
      run: sudo apt-get install curl -y

    - name: Download and run Codacy script
      run: |
        curl -Ls https://coverage.codacy.com/get.sh -o codacy_script.sh
        bash codacy_script.sh report -r coverage/coverage.cobertura.xml

